include Makefile.include

.PHONY: all
all: protogen

.PHONY: protogen
protogen:
	@echo "building protofile "
	protoc -I=/Users/bhakiyarajkalimuthu/go/src/github.com/bhakiyakalimuthu/fileshare/proto/ /Users/bhakiyarajkalimuthu/go/src/github.com/bhakiyakalimuthu/fileshare/proto/service.proto


